(() => {
  const LANGS = {
    ja:{name:'日本語',welcome:'MyFitへようこそ',intro:'筋トレが初めてでも大丈夫。まずは短く、無理なく始めましょう。',start:'かんたんに始める',lang:'言語',guide:'初心者ガイド',step1:'1. 種目を選ぶ',step2:'2. 重量と回数を入れる',step3:'3. セット完了を押して休む',prev:'前回',today:'今日の直前',sets:'今日のセット',rest:'休憩',finish:'終了',tip:'最初は軽めで、正しいフォームを優先してください。痛みが出たら中止してください。'},
    en:{name:'English',welcome:'Welcome to MyFit',intro:'New to strength training? Start short, light, and simple.',start:'Start simply',lang:'Language',guide:'Beginner guide',step1:'1. Choose an exercise',step2:'2. Enter weight and reps',step3:'3. Complete the set and rest',prev:'Previous',today:'Last set today',sets:'Sets today',rest:'Rest',finish:'Finish',tip:'Start light and prioritize good form. Stop if you feel pain.'},
    zh:{name:'中文',welcome:'欢迎使用 MyFit',intro:'第一次力量训练也没关系。从简单、轻量、短时间开始。',start:'简单开始',lang:'语言',guide:'新手指南',step1:'1. 选择动作',step2:'2. 输入重量和次数',step3:'3. 完成一组并休息',prev:'上次',today:'今天上一组',sets:'今日组数',rest:'休息',finish:'结束',tip:'从较轻重量开始，优先保持正确动作。如有疼痛请停止。'},
    es:{name:'Español',welcome:'Bienvenido a MyFit',intro:'¿Nuevo en fuerza? Empieza con poco peso, sesiones cortas y pasos simples.',start:'Empezar fácil',lang:'Idioma',guide:'Guía inicial',step1:'1. Elige un ejercicio',step2:'2. Introduce peso y repeticiones',step3:'3. Completa la serie y descansa',prev:'Anterior',today:'Última serie',sets:'Series hoy',rest:'Descanso',finish:'Terminar',tip:'Empieza ligero y prioriza la técnica. Detente si sientes dolor.'},
    fr:{name:'Français',welcome:'Bienvenue sur MyFit',intro:'Débutant en musculation ? Commencez léger, court et simplement.',start:'Commencer simplement',lang:'Langue',guide:'Guide débutant',step1:'1. Choisir un exercice',step2:'2. Saisir poids et répétitions',step3:'3. Valider la série et se reposer',prev:'Précédent',today:'Dernière série',sets:'Séries du jour',rest:'Repos',finish:'Terminer',tip:'Commencez léger et privilégiez la bonne technique. Arrêtez en cas de douleur.'},
    de:{name:'Deutsch',welcome:'Willkommen bei MyFit',intro:'Neu beim Krafttraining? Starte kurz, leicht und einfach.',start:'Einfach starten',lang:'Sprache',guide:'Einsteigerhilfe',step1:'1. Übung wählen',step2:'2. Gewicht und Wiederholungen eingeben',step3:'3. Satz abschließen und pausieren',prev:'Letztes Mal',today:'Letzter Satz',sets:'Sätze heute',rest:'Pause',finish:'Beenden',tip:'Beginne leicht und achte auf saubere Technik. Bei Schmerzen aufhören.'},
    pt:{name:'Português',welcome:'Bem-vindo ao MyFit',intro:'Novo no treino de força? Comece leve, curto e simples.',start:'Começar fácil',lang:'Idioma',guide:'Guia iniciante',step1:'1. Escolha um exercício',step2:'2. Informe peso e repetições',step3:'3. Conclua a série e descanse',prev:'Anterior',today:'Última série',sets:'Séries hoje',rest:'Descanso',finish:'Finalizar',tip:'Comece leve e priorize a boa técnica. Pare se sentir dor.'},
    ko:{name:'한국어',welcome:'MyFit에 오신 것을 환영합니다',intro:'근력운동이 처음이어도 괜찮습니다. 가볍고 짧게 시작하세요.',start:'쉽게 시작하기',lang:'언어',guide:'초보자 가이드',step1:'1. 운동 선택',step2:'2. 무게와 횟수 입력',step3:'3. 세트 완료 후 휴식',prev:'지난 기록',today:'오늘 직전 세트',sets:'오늘 세트',rest:'휴식',finish:'종료',tip:'가벼운 무게로 시작하고 정확한 자세를 우선하세요. 통증이 있으면 중단하세요.'}
  };
  let lang = localStorage.getItem('myfit-language') || ((navigator.language||'ja').slice(0,2));
  if(!LANGS[lang]) lang='en';
  const t=()=>LANGS[lang];
  const style=document.createElement('style');
  style.textContent=`
  .welcome-overlay{position:fixed;inset:0;z-index:3000;background:#f4f6f8;display:flex;align-items:center;justify-content:center;padding:24px}.welcome-card{width:min(100%,480px);background:#fff;border-radius:28px;padding:26px;box-shadow:0 18px 60px rgba(15,23,42,.15)}.welcome-card h2{font-size:30px;margin-bottom:10px}.welcome-card p{line-height:1.55}.welcome-card select{margin:8px 0 18px}.beginner-guide{background:#eef6ff;border-radius:14px;padding:9px 11px;margin-bottom:7px}.beginner-guide strong{display:block;font-size:12px;margin-bottom:4px}.beginner-steps{font-size:11px;line-height:1.45;color:#475569}.dashboard-info{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:5px 0 7px}.dashboard-info>div{background:#f8fafc;border-radius:10px;padding:6px;text-align:center;min-width:0}.dashboard-info span{display:block;font-size:9px;color:#6b7280}.dashboard-info strong{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.beginner-tip{font-size:10px;color:#64748b;margin:4px 0 0;line-height:1.3}.lang-mini{position:fixed;top:calc(8px + env(safe-area-inset-top));left:50%;transform:translateX(-50%);z-index:25;background:#fff;border:1px solid #e5e7eb;padding:4px 7px;border-radius:999px;font-size:10px;width:auto;margin:0}.workout-active .lang-mini{display:none}@media(max-width:380px){.welcome-card{padding:20px}.dashboard-info strong{font-size:11px}}
  `;document.head.appendChild(style);

  const guide=document.createElement('div');guide.className='beginner-guide';
  const second=document.querySelector('#workoutPanel > .card:nth-child(2)');if(second) second.insertBefore(guide,second.firstChild);
  const dash=document.createElement('div');dash.className='dashboard-info';if(second) second.insertBefore(dash,guide.nextSibling);
  const tip=document.createElement('p');tip.className='beginner-tip';if(second) second.appendChild(tip);

  const langMini=document.createElement('select');langMini.className='lang-mini';Object.entries(LANGS).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.name;langMini.appendChild(o)});langMini.value=lang;document.body.appendChild(langMini);
  langMini.onchange=()=>setLang(langMini.value);

  function setLang(v){lang=v;localStorage.setItem('myfit-language',lang);document.documentElement.lang=lang;langMini.value=lang;renderStatic();renderDash();}
  function renderStatic(){guide.innerHTML=`<strong>${t().guide}</strong><div class="beginner-steps">${t().step1} → ${t().step2} → ${t().step3}</div>`;tip.textContent=t().tip;document.getElementById('finishWorkoutBtn').textContent=t().finish;}
  function currentEx(){return typeof currentExercise==='function'?currentExercise():null}
  function lastToday(){const ex=currentEx();if(!ex||!window.data?.activeWorkout)return null;const a=data.activeWorkout.sets.filter(s=>s.exerciseId===ex.id);return a[a.length-1]||null}
  function renderDash(){const ex=currentEx();const prev=ex&&typeof findPreviousSet==='function'?findPreviousSet(ex.id):null;const last=lastToday();const count=window.data?.activeWorkout?.sets?.filter(s=>s.exerciseId===ex?.id).length||0;const desc=s=>s&&ex&&typeof describeSet==='function'?describeSet(s,ex):'—';dash.innerHTML=`<div><span>${t().prev}</span><strong>${desc(prev)}</strong></div><div><span>${t().today}</span><strong>${desc(last)}</strong></div><div><span>${t().sets}</span><strong>${count}</strong></div>`;}
  function welcome(){if(localStorage.getItem('myfit-onboarded'))return;const o=document.createElement('div');o.className='welcome-overlay';o.innerHTML=`<div class="welcome-card"><h2>${t().welcome}</h2><p>${t().intro}</p><label>${t().lang}<select id="welcomeLang"></select></label><p><strong>${t().guide}</strong><br>${t().step1}<br>${t().step2}<br>${t().step3}</p><button class="primary full" id="welcomeStart">${t().start}</button></div>`;document.body.appendChild(o);const s=o.querySelector('#welcomeLang');Object.entries(LANGS).forEach(([k,v])=>{const x=document.createElement('option');x.value=k;x.textContent=v.name;s.appendChild(x)});s.value=lang;s.onchange=()=>{setLang(s.value);o.remove();welcome()};o.querySelector('#welcomeStart').onclick=()=>{localStorage.setItem('myfit-onboarded','1');o.remove()};}
  document.getElementById('exerciseSelect')?.addEventListener('change',()=>setTimeout(renderDash,0));document.getElementById('completeSetBtn')?.addEventListener('click',()=>setTimeout(renderDash,20));
  new MutationObserver(()=>renderDash()).observe(document.getElementById('setsList'),{childList:true,subtree:true});
  setLang(lang);welcome();
})();
