(() => {
  const COPY = {
    en:{elapsed:'Elapsed',todayWorkout:"Today's workout",start:'Start',exerciseSection:'Exercises',add:'Add',noPrevious:'No previous record',currentSet:'Current Set',memo:'Note',complete:'Complete Set',recorded:'Recorded Sets',noRecords:'No Sets recorded yet',finish:'Finish workout',historyTitle:'Workout history',export:'Export',manage:'Manage exercises',tracking:'Tracking format',defaultRest:'Default Rest',register:'Add Exercise',settings:'Settings',data:'Data management',stored:'Records are stored in this browser on this device.',backup:'Import backup',deleteAll:'Delete all data',home:'Add to Home Screen',homeHelp:'In Safari, tap Share and choose “Add to Home Screen”.',today:'Today',history:'History',exercises:'Exercises',delete:'Delete',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Close',done:'Nice work'},
    ja:{elapsed:'経過時間',todayWorkout:'今日のトレーニング',start:'開始する',exerciseSection:'種目',add:'追加',noPrevious:'前回記録はありません',currentSet:'今回の Set',memo:'メモ',complete:'Set 完了',recorded:'記録済み Sets',noRecords:'まだ Set 記録がありません',finish:'トレーニング終了',historyTitle:'トレーニング履歴',export:'書き出し',manage:'種目管理',tracking:'記録形式',defaultRest:'標準 Rest',register:'Exercise を登録',settings:'設定',data:'データ管理',stored:'記録はこの端末のブラウザ内に保存されます。',backup:'バックアップを読み込む',deleteAll:'すべてのデータを削除',home:'ホーム画面への追加',homeHelp:'Safariの共有ボタンから「ホーム画面に追加」を選んでください。',today:'今日',history:'履歴',exercises:'種目',delete:'削除',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'閉じる',done:'お疲れさまでした'},
    es:{elapsed:'Tiempo',todayWorkout:'Entrenamiento de hoy',start:'Empezar',exerciseSection:'Ejercicios',add:'Añadir',noPrevious:'No hay registro anterior',currentSet:'Set actual',memo:'Nota',complete:'Completar Set',recorded:'Sets registrados',noRecords:'Aún no hay Sets registrados',finish:'Terminar entrenamiento',historyTitle:'Historial de entrenamiento',export:'Exportar',manage:'Gestión de ejercicios',tracking:'Formato de registro',defaultRest:'Rest predeterminado',register:'Añadir Exercise',settings:'Ajustes',data:'Gestión de datos',stored:'Los registros se guardan en este navegador y dispositivo.',backup:'Importar copia de seguridad',deleteAll:'Eliminar todos los datos',home:'Añadir a la pantalla de inicio',homeHelp:'En Safari, pulsa Compartir y elige “Añadir a pantalla de inicio”.',today:'Hoy',history:'Historial',exercises:'Ejercicios',delete:'Eliminar',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Cerrar',done:'Buen trabajo'},
    fr:{elapsed:'Temps',todayWorkout:"Entraînement d’aujourd’hui",start:'Commencer',exerciseSection:'Exercices',add:'Ajouter',noPrevious:'Aucun enregistrement précédent',currentSet:'Set actuel',memo:'Note',complete:'Valider le Set',recorded:'Sets enregistrés',noRecords:'Aucun Set enregistré',finish:"Terminer l’entraînement",historyTitle:"Historique d’entraînement",export:'Exporter',manage:'Gestion des exercices',tracking:"Format d’enregistrement",defaultRest:'Rest par défaut',register:'Ajouter Exercise',settings:'Réglages',data:'Gestion des données',stored:'Les données sont enregistrées dans ce navigateur sur cet appareil.',backup:'Importer une sauvegarde',deleteAll:'Supprimer toutes les données',home:"Ajouter à l’écran d’accueil",homeHelp:'Dans Safari, touchez Partager puis « Ajouter à l’écran d’accueil ».',today:"Aujourd’hui",history:'Historique',exercises:'Exercices',delete:'Supprimer',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Fermer',done:'Bravo'},
    ru:{elapsed:'Время',todayWorkout:'Сегодняшняя тренировка',start:'Начать',exerciseSection:'Упражнения',add:'Добавить',noPrevious:'Предыдущих записей нет',currentSet:'Текущий Set',memo:'Заметка',complete:'Завершить Set',recorded:'Записанные Sets',noRecords:'Пока нет записанных Sets',finish:'Завершить тренировку',historyTitle:'История тренировок',export:'Экспорт',manage:'Управление упражнениями',tracking:'Формат записи',defaultRest:'Rest по умолчанию',register:'Добавить Exercise',settings:'Настройки',data:'Управление данными',stored:'Записи сохраняются в браузере на этом устройстве.',backup:'Импортировать резервную копию',deleteAll:'Удалить все данные',home:'Добавить на главный экран',homeHelp:'В Safari нажмите «Поделиться» и выберите добавление на главный экран.',today:'Сегодня',history:'История',exercises:'Упражнения',delete:'Удалить',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Закрыть',done:'Отлично'},
    de:{elapsed:'Zeit',todayWorkout:'Heutiges Training',start:'Starten',exerciseSection:'Übungen',add:'Hinzufügen',noPrevious:'Keine vorherige Aufzeichnung',currentSet:'Aktueller Set',memo:'Notiz',complete:'Set abschließen',recorded:'Gespeicherte Sets',noRecords:'Noch keine Sets gespeichert',finish:'Training beenden',historyTitle:'Trainingsverlauf',export:'Exportieren',manage:'Übungen verwalten',tracking:'Aufzeichnungsformat',defaultRest:'Standard-Rest',register:'Exercise hinzufügen',settings:'Einstellungen',data:'Datenverwaltung',stored:'Aufzeichnungen werden in diesem Browser auf diesem Gerät gespeichert.',backup:'Backup importieren',deleteAll:'Alle Daten löschen',home:'Zum Home-Bildschirm hinzufügen',homeHelp:'In Safari „Teilen“ und dann „Zum Home-Bildschirm“ wählen.',today:'Heute',history:'Verlauf',exercises:'Übungen',delete:'Löschen',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Schließen',done:'Gut gemacht'},
    pt:{elapsed:'Tempo',todayWorkout:'Treino de hoje',start:'Começar',exerciseSection:'Exercícios',add:'Adicionar',noPrevious:'Sem registro anterior',currentSet:'Set atual',memo:'Nota',complete:'Concluir Set',recorded:'Sets registrados',noRecords:'Ainda não há Sets registrados',finish:'Finalizar treino',historyTitle:'Histórico de treino',export:'Exportar',manage:'Gerenciar exercícios',tracking:'Formato de registro',defaultRest:'Rest padrão',register:'Adicionar Exercise',settings:'Configurações',data:'Gerenciamento de dados',stored:'Os registros são salvos neste navegador e dispositivo.',backup:'Importar backup',deleteAll:'Excluir todos os dados',home:'Adicionar à tela inicial',homeHelp:'No Safari, toque em Compartilhar e escolha “Adicionar à Tela de Início”.',today:'Hoje',history:'Histórico',exercises:'Exercícios',delete:'Excluir',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'Fechar',done:'Muito bem'},
    zh:{elapsed:'时间',todayWorkout:'今天的训练',start:'开始',exerciseSection:'动作',add:'添加',noPrevious:'没有之前的记录',currentSet:'当前 Set',memo:'备注',complete:'完成 Set',recorded:'已记录 Sets',noRecords:'还没有 Set 记录',finish:'结束训练',historyTitle:'训练记录',export:'导出',manage:'动作管理',tracking:'记录方式',defaultRest:'默认 Rest',register:'添加 Exercise',settings:'设置',data:'数据管理',stored:'记录保存在此设备的浏览器中。',backup:'导入备份',deleteAll:'删除全部数据',home:'添加到主屏幕',homeHelp:'在 Safari 中点击分享，然后选择“添加到主屏幕”。',today:'今天',history:'记录',exercises:'动作',delete:'删除',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'关闭',done:'做得好'},
    ko:{elapsed:'시간',todayWorkout:'오늘의 트레이닝',start:'시작',exerciseSection:'운동',add:'추가',noPrevious:'이전 기록 없음',currentSet:'현재 Set',memo:'메모',complete:'Set 완료',recorded:'기록된 Sets',noRecords:'아직 Set 기록이 없습니다',finish:'트레이닝 종료',historyTitle:'트레이닝 기록',export:'내보내기',manage:'운동 관리',tracking:'기록 방식',defaultRest:'기본 Rest',register:'Exercise 추가',settings:'설정',data:'데이터 관리',stored:'기록은 이 기기의 브라우저에 저장됩니다.',backup:'백업 가져오기',deleteAll:'모든 데이터 삭제',home:'홈 화면에 추가',homeHelp:'Safari에서 공유를 누르고 “홈 화면에 추가”를 선택하세요.',today:'오늘',history:'기록',exercises:'운동',delete:'삭제',standard:'Weight + Reps',bodyweight:'Bodyweight (Reps only)',sided:'Left / Right',close:'닫기',done:'수고했어요'}
  };
  const getLang=()=>{const x=localStorage.getItem('myfit-language')||'en';return COPY[x]?x:'en'};
  const c=()=>COPY[getLang()];
  const txt=(sel,v)=>{const e=document.querySelector(sel);if(e)e.textContent=v};
  const label=(sel,v)=>{const e=document.querySelector(sel);if(!e)return;const n=[...e.childNodes].find(x=>x.nodeType===3&&x.textContent.trim());if(n)n.textContent=v};
  function applyExerciseCards(){
    if(typeof data==='undefined')return;
    document.querySelectorAll('#exerciseList .exercise-item').forEach((card,i)=>{
      const ex=data.exercises[i]; if(!ex)return;
      const meta=card.querySelector('.set-meta');
      const type=ex.type==='standard'?c().standard:ex.type==='bodyweight'?c().bodyweight:c().sided;
      if(meta)meta.textContent=`${type} · Rest ${ex.restSeconds}s`;
      const del=card.querySelector('.delete-btn'); if(del)del.textContent=c().delete;
    });
  }
  function apply(){
    document.documentElement.lang=getLang();
    txt('.elapsed-wrap span',c().elapsed); txt('#todayView .hero .muted',c().todayWorkout); txt('#startWorkoutBtn',c().start);
    txt('#workoutPanel>.card:first-child h3','Exercise'); txt('#addExerciseBtn',`+ ${c().add}`);
    const p=document.getElementById('previousRecord'); if(p&&(/ありません|No previous|Aucun|Sem registro|Keine|нет/i.test(p.textContent)))p.textContent=c().noPrevious;
    txt('#workoutPanel>.card:nth-child(2)>h3',c().currentSet); label('#standardInputs label:nth-child(1)','Weight'); label('#standardInputs label:nth-child(2)','Reps'); label('#bodyweightInputs label','Reps');
    label('#sidedInputs label:nth-child(1)','Right Weight');label('#sidedInputs label:nth-child(2)','Right Reps');label('#sidedInputs label:nth-child(3)','Left Weight');label('#sidedInputs label:nth-child(4)','Left Reps');label('.memo-label',c().memo);txt('#completeSetBtn',c().complete);
    txt('#workoutPanel>.card:nth-child(3) h3',c().recorded); const sl=document.getElementById('setsList');if(sl&&sl.classList.contains('empty'))sl.textContent=c().noRecords;txt('.timer-card .muted','Rest Timer');txt('#finishWorkoutBtn',c().finish);
    txt('#historyView h2',c().historyTitle);txt('#exportBtn',c().export);txt('#exercisesView h2',c().manage);label('#exerciseForm label:nth-of-type(1)','Exercise');label('#exerciseForm label:nth-of-type(2)',c().tracking);label('#exerciseForm label:nth-of-type(3)',c().defaultRest);
    const opts=document.querySelectorAll('#exerciseTypeInput option');if(opts[0])opts[0].textContent=c().standard;if(opts[1])opts[1].textContent=c().bodyweight;if(opts[2])opts[2].textContent=c().sided;document.querySelectorAll('#restSecondsInput option').forEach(o=>o.textContent=`${o.value}s`);txt('#exerciseForm button[type="submit"]',c().register);
    txt('#settingsView h2',c().settings);txt('#settingsView .card:nth-of-type(1) h3',c().data);txt('#settingsView .card:nth-of-type(1) .muted',c().stored);label('#settingsView .file-button',c().backup);txt('#resetBtn',c().deleteAll);txt('#settingsView .card:nth-of-type(2) h3',c().home);txt('#settingsView .card:nth-of-type(2) .muted',c().homeHelp);
    const nav=document.querySelectorAll('.bottom-nav button');const nv=[c().today,c().history,c().exercises,c().settings];nav.forEach((b,i)=>{const n=[...b.childNodes].find(x=>x.nodeType===3);if(n)n.textContent=nv[i]||''});
    txt('#summaryDialog h2',c().done);txt('#closeSummaryBtn',c().close);applyExerciseCards();
  }
  document.addEventListener('myfit-language-change',()=>setTimeout(apply,0));
  document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>setTimeout(apply,30)));
  document.getElementById('exerciseForm')?.addEventListener('submit',()=>setTimeout(apply,40));
  document.addEventListener('click',e=>{if(e.target.closest('[data-delete-exercise]'))setTimeout(apply,40)});
  apply();
  window.MyFitLocale={apply};
})();
