(() => {
  const style=document.createElement('style');style.textContent=`.timer-fab{position:fixed;right:max(16px,calc((100vw - 760px)/2 + 16px));bottom:calc(78px + env(safe-area-inset-bottom));z-index:20;border:0;border-radius:999px;padding:13px 17px;background:#111827;color:#fff;font-weight:900;box-shadow:0 8px 24px rgba(17,24,39,.24)}.timer-fab[hidden],.timer-overlay[hidden]{display:none!important}.timer-overlay{position:fixed;inset:0;z-index:1000;display:flex;flex-direction:column;justify-content:space-between;min-height:100dvh;padding:calc(18px + env(safe-area-inset-top)) 18px calc(18px + env(safe-area-inset-bottom));background:#111827;color:#fff}.timer-overlay.alarm{animation:myfitTimerFlash 1.2s steps(1,end) infinite}@keyframes myfitTimerFlash{0%,49%{background:#111827;color:#fff}50%,100%{background:#f8fafc;color:#111827}}.timer-overlay-top{display:flex;justify-content:space-between;align-items:center}.timer-overlay-label{font-size:12px;letter-spacing:.16em;font-weight:900;opacity:.72}.timer-overlay-close{border:1px solid currentColor;background:transparent;color:inherit;border-radius:999px;padding:9px 12px}.timer-overlay-main{text-align:center;width:100%;max-width:560px;margin:auto}.timer-overlay-status{font-size:22px;font-weight:900}.timer-overlay-time{font-size:clamp(88px,25vw,160px);font-weight:950;letter-spacing:-.07em;margin:18px 0 20px}.timer-overlay-next{font-size:14px;opacity:.75;margin:0 0 24px}.timer-overlay-adjust{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px}.timer-overlay button{min-height:52px}.timer-overlay-adjust button,.timer-overlay-toggle{border:1px solid rgba(255,255,255,.28);background:rgba(255,255,255,.12);color:inherit;border-radius:16px;font-weight:900}.timer-overlay-toggle{width:100%;font-size:18px}.timer-overlay-stop{width:100%;max-width:560px;margin:16px auto 0;border:0;border-radius:17px;background:#fff;color:#111827;font-size:17px;font-weight:950}.timer-overlay.alarm .timer-overlay-stop{background:#111827;color:#fff}@media(prefers-reduced-motion:reduce){.timer-overlay.alarm{animation:none;background:#f8fafc;color:#111827}}`;document.head.appendChild(style);
  const fab=document.createElement('button');fab.className='timer-fab';fab.textContent='⏱ REST';fab.hidden=true;document.body.appendChild(fab);
  const overlay=document.createElement('section');overlay.className='timer-overlay';overlay.hidden=true;overlay.innerHTML=`<div class="timer-overlay-top"><p class="timer-overlay-label">REST</p><button class="timer-overlay-close">×</button></div><div class="timer-overlay-main"><p class="timer-overlay-status">Rest</p><div class="timer-overlay-time">01:30</div><p class="timer-overlay-next"></p><div class="timer-overlay-adjust"><button class="minus">−30</button><button class="plus">＋30</button></div><button class="timer-overlay-toggle">Pause</button></div><button class="timer-overlay-stop">Finish rest</button>`;document.body.appendChild(overlay);
  const time=overlay.querySelector('.timer-overlay-time'),status=overlay.querySelector('.timer-overlay-status'),next=overlay.querySelector('.timer-overlay-next'),toggle=overlay.querySelector('.timer-overlay-toggle'),stop=overlay.querySelector('.timer-overlay-stop');let audioContext=null,alarmInterval=null,alarmActive=false,previousRemaining=Number(restRemaining);
  const language=()=>localStorage.getItem('myfit-language')||'en';const tx={en:['Rest','Rest finished','Next: start when you are ready','Finish rest','Pause','Resume'],ja:['休憩','休憩終了','次：準備ができたら開始','休憩を終了','一時停止','再開'],ru:['Отдых','Отдых окончен','Далее: начинайте, когда будете готовы','Завершить отдых','Пауза','Продолжить'],fr:['Repos','Repos terminé','Ensuite : commencez quand vous êtes prêt','Terminer le repos','Pause','Reprendre'],es:['Descanso','Descanso terminado','Siguiente: empieza cuando estés listo','Terminar descanso','Pausa','Continuar'],de:['Pause','Pause beendet','Als Nächstes: starten, wenn du bereit bist','Pause beenden','Pause','Weiter'],pt:['Descanso','Descanso terminado','Próximo: comece quando estiver pronto','Terminar descanso','Pausa','Continuar'],zh:['休息','休息结束','下一步：准备好后开始','结束休息','暂停','继续'],ko:['휴식','휴식 종료','다음: 준비되면 시작','휴식 종료','일시정지','계속']};const c=()=>tx[language()]||tx.en;
  function unlock(){try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume()}catch{}}
  function bell(){if(!audioContext)return;try{const n=audioContext.currentTime;[0,.16,.34].forEach((d,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=[880,1174,880][i];g.gain.setValueAtTime(.0001,n+d);g.gain.exponentialRampToValueAtTime(.22,n+d+.015);g.gain.exponentialRampToValueAtTime(.0001,n+d+.22);o.connect(g);g.connect(audioContext.destination);o.start(n+d);o.stop(n+d+.24)})}catch{}}
  function alarm(){if(alarmActive)return;alarmActive=true;overlay.hidden=false;overlay.classList.add('alarm');status.textContent=c()[1];next.textContent=c()[2];stop.textContent=c()[3];bell();alarmInterval=setInterval(bell,1500);if(navigator.vibrate)navigator.vibrate([250,120,250,120,400])}
  function stopAlarm(){alarmActive=false;clearInterval(alarmInterval);overlay.classList.remove('alarm');if(navigator.vibrate)navigator.vibrate(0)}
  function update(){time.textContent=formatTime(restRemaining);if(!alarmActive){status.textContent=c()[0];next.textContent=c()[2];stop.textContent=c()[3];toggle.textContent=restRunning?c()[4]:c()[5]}}
  function open(){unlock();overlay.hidden=false;update()}
  function returnToReady(){stopAlarm();clearInterval(restInterval);restRunning=false;const ex=typeof currentExercise==='function'?currentExercise():null;resetRest(ex?.restSeconds||90);previousRemaining=Number(restRemaining);overlay.hidden=true;setTimeout(()=>window.MyFitCoach?.ready(),80)}
  fab.onclick=open;toggle.onclick=()=>{unlock();els.toggleTimerBtn.click();update()};overlay.querySelector('.minus').onclick=()=>{els.minus30Btn.click();update()};overlay.querySelector('.plus').onclick=()=>{els.plus30Btn.click();update()};stop.onclick=returnToReady;overlay.querySelector('.timer-overlay-close').onclick=returnToReady;
  els.completeSetBtn.addEventListener('click',()=>{unlock();setTimeout(()=>{if(restRunning)open()},0)});
  setInterval(()=>{fab.hidden=els.workoutPanel.classList.contains('hidden')||!overlay.hidden;const r=Number(restRemaining);if(previousRemaining>0&&r<=0&&!restRunning)alarm();previousRemaining=r;if(!overlay.hidden)update()},150);
})();